import Mimic

// A protocol you'd normally want to fake out in a test.
@Mockable
protocol WeatherService {
    var lastCity: String? { get }
    func temperature(in city: String) async throws -> Double
    func refresh()
}

// `MockWeatherService` is generated by the `@Mockable` macro above.
let mock = MockWeatherService()
mock.lastCity = "Paris"
mock.temperatureHandler = { city in city == "Paris" ? 95.0 : 60.0 }

let temp = try await mock.temperature(in: "Paris")
mock.refresh()

print("lastCity:        \(mock.lastCity ?? "nil")")
print("temperature:     \(temp)")
print("temperature args:\(mock.temperatureCalls)")
print("refresh calls:   \(mock.refreshCallCount)")
